version: '3.8'

services:
  # Eureka Naming Server - Ultra minimal
  naming-server:
    build:
      context: ./naming-server
    container_name: eureka-naming-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-network
    # Ultra-minimal resource allocation
    mem_limit: 128m
    cpus: 0.25
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 3s
      retries: 10

  # User Service Instance 1 - Ultra minimal
  user-service-1:
    build:
      context: ./user-service
    container_name: user-service-1
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - EUREKA_INSTANCE_INSTANCEID=user-service:8081
      # Spring Boot retry and startup configuration
      - EUREKA_CLIENT_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_CLIENT_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=3
      - EUREKA_CLIENT_INSTANCE_REGISTRATION_ENABLED=true
      - EUREKA_CLIENT_INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS=5
      - EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS=30
      - EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS=30
      # Spring Boot startup configuration
      - SPRING_CLOUD_DISCOVERY_CLIENT_FAIL_FAST=false
      - SPRING_CLOUD_DISCOVERY_CLIENT_REGISTER_HEALTH_INDICATOR=false
    networks:
      - microservice-network
    depends_on:
      naming-server:
        condition: service_healthy
    # Ultra-minimal resource allocation
    mem_limit: 128m
    cpus: 0.25
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/actuator/health"]
      interval: 15s
      timeout: 3s
      retries: 10

  # User Service Instance 2 - Ultra minimal
  user-service-2:
    build:
      context: ./user-service
    container_name: user-service-2
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - EUREKA_INSTANCE_INSTANCEID=user-service:8082
      # Spring Boot retry and startup configuration
      - EUREKA_CLIENT_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_CLIENT_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=3
      - EUREKA_CLIENT_INSTANCE_REGISTRATION_ENABLED=true
      - EUREKA_CLIENT_INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS=5
      - EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS=30
      - EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS=30
      # Spring Boot startup configuration
      - SPRING_CLOUD_DISCOVERY_CLIENT_FAIL_FAST=false
      - SPRING_CLOUD_DISCOVERY_CLIENT_REGISTER_HEALTH_INDICATOR=false
    networks:
      - microservice-network
    depends_on:
      naming-server:
        condition: service_healthy
    # Ultra-minimal resource allocation
    mem_limit: 128m
    cpus: 0.25
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8082/actuator/health"]
      interval: 15s
      timeout: 3s
      retries: 10

  # Hello Service - Ultra minimal
  hello-service:
    build:
      context: ./hello-service
    container_name: hello-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      # Spring Boot retry and startup configuration
      - EUREKA_CLIENT_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_CLIENT_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=3
      - EUREKA_CLIENT_INSTANCE_REGISTRATION_ENABLED=true
      - EUREKA_CLIENT_INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS=5
      - EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS=30
      - EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS=30
      # Spring Boot startup configuration
      - SPRING_CLOUD_DISCOVERY_CLIENT_FAIL_FAST=false
      - SPRING_CLOUD_DISCOVERY_CLIENT_REGISTER_HEALTH_INDICATOR=false
      # Load balancer configuration
      - SPRING_CLOUD_LOADBALANCER_ENABLED=true
    networks:
      - microservice-network
    depends_on:
      naming-server:
        condition: service_healthy
      user-service-1:
        condition: service_healthy
      user-service-2:
        condition: service_healthy
    # Ultra-minimal resource allocation
    mem_limit: 128m
    cpus: 0.25
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 3s
      retries: 10

networks:
  microservice-network:
    driver: bridge
